# Site settings
name: Arnav Deep
title: Arnav Deep | Software Engineer and Data Scientist
description: Focused on building solutions for billions.
url: https://arnav-deep.github.io/
baseurl: ''
email: arnavd4@gmail.com
cover: https://arnav-deep.github.io/img/og.png
logo: https://arnav-deep.github.io/img/emojis/technologist.png
resume: https://bit.ly/arnav-deep-resume
social:
  - title: email
    url: mailto:arnavd4@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/arnav-deep
  - title: github
    url: https://github.com/arnav-deep
  - title: codechef
    url: https://codechef.com/users/thrown
  - title: twitter
    url: https://twitter.com/arnavd4
  - title: instagram
    url: https://instagram.com/arnav_deep

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
